### ISSUE TITLE
camera a/f broken

### ISSUE THREAD

**Issue by djdisodo** [LeEcoDevs/android_device_leeco_s2#2]
i'm using rom from xda on my leeco le s3 32gb
but camera auto focus is working but wrong
it wasn't able to catch focus and seems blury

also i found that there was no cpu init file
(/system/vendor/etc/init/hw/init.qcom.power.rc)

+is there a newer prebuilt version of this?

**Comment by ThEMarD** [comment]
odds are your camera actuator has failed as that is a hardware issue.

init.qcom.power.rc is a custom init script. s2 uses the CAF shell scripts to set CPU values.

This isn't a support forum. I recommend going to LeEco Le 2's XDA forums or ask in the Telegram group for any solutions to your camera issue.
